namespace: logging
service:
  name: demospringmonitor
  port: 80
  image:
    path: nginx
    tag: latest

ingress:
  host: app.cloudrural.net
  path: "/nginx"

#environments:

health:
  endpoint: /actuator/health
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 10
