namespace: app
service:
  name: demospringmonitor
  port: 8080
  image:
    path: 065740665475.dkr.ecr.us-east-2.amazonaws.com/crops/demospringmonitor
    tag: v2021.11

ingress:
  host: app.cloudrural.com
  path: "/demospringmonitor"

#environments:

health:
  endpoint: /actuator/health
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 10